CREATE OR REPLACE NOTEBOOK IDENTIFIER('"DEMO_DB"."DATA"."USAGE_REPORT"')
    FROM '@"DEMO_DB"."INTEGRATIONS"."DEMO_GIT_REPO"/branches/main/notebooks/02_usage_report/'
    QUERY_WAREHOUSE = 'DEMO_WH'
    MAIN_FILE = '02_usage_report.ipynb';

ALTER NOTEBOOK "DEMO_DB"."DATA"."USAGE_REPORT" ADD LIVE VERSION FROM LAST;

